# Project: 2019033
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 2019033.o
LINKOBJ  = 2019033.o
LIBS     = -L"D:/application/Dev-Cpp/MinGW64/lib" -L"D:/application/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/application/Dev-Cpp/MinGW64/include" -I"D:/application/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/application/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/application/Dev-Cpp/MinGW64/include" -I"D:/application/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/application/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/application/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 2019033.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

2019033.o: 2019033.cpp
	$(CPP) -c 2019033.cpp -o 2019033.o $(CXXFLAGS)
